name: Copy and Replace MD Files

on:
    push:
        branches:
            - master # Trigger on pushes to the master branch

permissions:
    contents: write # Grant write permission to the repository

jobs:
    copy-and-replace:
        runs-on: ubuntu-latest

        steps:
            # Checkout the repository and fetch all branches
            - name: Checkout repository
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0 # Fetch all history for all branches and tags

            # Create or switch to 'files-qmd' branch
            - name: Switch to 'files-qmd' branch
              run: |
                  if git show-ref --verify --quiet refs/heads/files-qmd; then
                    git checkout files-qmd
                  else
                    git checkout -b files-qmd
                  fi

            # Run the script to replace .md with .qmd and add header
            - name: Convert .md to .qmd and add header
              run: |
                  chmod +x ./scripts/convert-md-to-qmd.sh
                  ./scripts/convert-md-to-qmd.sh

            # Commit and push changes
            - name: Commit and push changes
              env:
                  GIT_AUTHOR_NAME: github-actions[bot]
                  GIT_AUTHOR_EMAIL: github-actions[bot]@users.noreply.github.com
                  GIT_COMMITTER_NAME: github-actions[bot]
                  GIT_COMMITTER_EMAIL: github-actions[bot]@users.noreply.github.com
              run: |
                  git add -A
                  git commit -m "Replace .md files with .qmd and add/modify headers" || echo "No changes to commit"
                  git push origin files-qmd
