name: Copy and Replace MD Files

on:
    push:
        branches:
            - master # Trigger on pushes to the master branch (or change to your source branch)

jobs:
    copy-and-replace:
        runs-on: ubuntu-latest

        steps:
            # Checkout the repository
            - name: Checkout the repository
              uses: actions/checkout@v3

            # Fetch all branches
            - name: Fetch all branches
              run: git fetch --all

            # Switch to the target branch (e.g., 'files-qmd')
            - name: Checkout the target branch
              run: |
                  git checkout files-qmd || git checkout -b files-qmd

            # Copy files from the source branch (e.g., 'master') to the target branch
            - name: Copy files from source branch to target branch
              run: |
                  git checkout master -- . # Adjust if your source branch is different
                  git reset HEAD # Unstage files

            # Replace .md files with .qmd files and add the header
            - name: Replace .md with .qmd and add header
              run: |
                  for file in $(find . -type f -name "*.md"); do
                      filename=$(basename "$file" .md)
                      # Move .md to .qmd
                      mv "$file" "${file%.md}.qmd"
                      # Add YAML header to the new .qmd file
                      echo -e "---\ntitle: $filename\n---\n$(cat "${file%.md}.qmd")" > "${file%.md}.qmd"
                    done

            # Configure git user for committing
            - name: Configure Git user
              run: |
                  git config --global user.name "github-actions"
                  git config --global user.email "github-actions@github.com"

            # Add and commit changes
            - name: Commit changes
              run: |
                  git add .
                  git commit -m "Replace .md files with .qmd and add header"

            # Push changes to the target branch
            - name: Push changes
              run: |
                  git push origin files-qmd
