name: Copy and Replace MD Files

on:
    push:
        branches:
            - main # Trigger on pushes to the main branch (or change to your source branch)

permissions:
    contents: write # Grant write permission to the repository

jobs:
    copy-and-replace:
        runs-on: ubuntu-latest

        steps:
            # Checkout the repository
            - name: Checkout the repository
              uses: actions/checkout@v3

            # Fetch all branches
            - name: Fetch all branches
              run: git fetch --all

            # Switch to the target branch (e.g., 'files-qmd')
            - name: Checkout the target branch
              run: |
                  git checkout files-qmd || git checkout -b files-qmd

            # Run the script to replace .md with .qmd and add header
            - name: Replace .md with .qmd and add header
              run: |
                  chmod +x ./convert-md-to-qmd.sh
                  ./convert-md-to-qmd.sh

            # Configure git user for committing
            - name: Configure Git user
              run: |
                  git config --global user.name "github-actions"
                  git config --global user.email "github-actions@github.com"

            # Add and commit changes
            - name: Commit changes
              run: |
                  git add .
                  git commit -m "Replace .md files with .qmd and add/modify headers"

            # Push changes to the target branch
            - name: Push changes
              run: |
                  git push origin files-qmd
